# Generated by Django 4.1.3 on 2023-08-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contract',
            new_name='Contact',
        ),
    ]
